status_path "~/.local/share/pimsync/status/"

## calendars
storage nuthouse_calendars {
  type caldav
  url https://cloud.nuthouse.de/remote.php/dav/principals/users/nutcase/
  username nutcase
  password {
    shell grep cloud.nuthouse.de ~/.authinfo | awk \'FNR == 1 {print $8}\'
  }
  interval 120
}
storage local_calendars {
  type vdir/icalendar
  path ~/.calendars/
  fileext ics
  interval 120
}
pair calendars {
  storage_a nuthouse_calendars
  storage_b local_calendars
  collections from a
  #conflict_resolution cmd emacsclient -c
  # conflict_resolution keep a
}

## contacts
storage nuthouse_contacts {
  type carddav
  url https://cloud.nuthouse.de/remote.php/dav/principals/users/nutcase/
  username nutcase
  password {
    shell grep cloud.nuthouse.de ~/.authinfo | awk \'FNR == 1 {print $8}\'
  }
  interval 120
}
storage local_contacts {
  type vdir/vcard
  path ~/.contacts/
  fileext vcf
  interval 120
}
pair contacts {
  storage_a nuthouse_contacts
  storage_b local_contacts
  collection {
    alias Kontakte
    id_a Kontakte
    id_b Kontakte
  }
}
