
(require 'package)
(setq package-archives '(("elpa" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(package-install 'khalel)
(require 'khalel)
(setq khalel-default-calendar "Persönlich")
(setq khalel-import-org-file (concat org-directory "/" "calendar.org"))
(setq khalel-import-start-date "-2m")
(setq khalel-import-end-date "+12m")
(setq khalel-import-org-file-confirm-overwrite nil)
(setq khalel-import-format "* {title} {cancelled} :{calendar}:
:PROPERTIES:
:CALENDAR: {calendar}
:CATEGORY: {calendar}
:LOCATION: {location}
:ID: {uid}
:END:
- When: <{start-date-long} {start-time}>--<{end-date-long} {end-time}>
- Where: {location}
- Description: {description}
- URL: {url}
- Organizer: {organizer}

[[elisp:(khalel-edit-calendar-event)][Edit this event]]    [[elisp:(progn (khalel-run-vdirsyncer) (khalel-import-events))][Sync and update all]]
")
(setq khalel-import-org-file-read-only nil)
(setq khalel-import-org-file-header "# -*- buffer-read-only: 1; auto-revert-mode: 1; -*-
#+TITLE: khalel imported calendar events

#+COLUMNS: %ITEM %TIMESTAMP %LOCATION %CALENDAR

*NOTE*: this file has been generated by [[elisp:(khalel-import-events)][khalel-import-events]] and /any changes to this document will be lost on the next import/!
Instead, use =khalel-edit-calendar-event= or =khal edit= to edit the underlying calendar entries, then re-import them here.

You can use [[elisp:(khalel-run-vdirsyncer)][khalel-run-vdirsyncer]] to synchronize with remote calendars.

Consider adding this file to your list of agenda files so that events show up there.

")
