import = ["/home/flake/.config/alacritty/alacritty-themes/themes/modus-vivendi.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"
blinking = "On"

[window.padding]
x = 10
y = 7